// =============================================================
// CATÁLOGOS ONLINE — PAIIA
// Lista de catálogos automotivos EXTERNOS (links diretos).
// O PAIIA apenas abre a fonte externa em nova aba:
//   - sem scraping, sem copiar dados, sem importar para o Supabase;
//   - login/cadastro/assinatura são feitos pelo próprio usuário no site externo;
//   - o PAIIA não armazena senha, cartão ou dados de pagamento.
//
// PARA ADICIONAR UM CATÁLOGO: basta incluir um novo objeto no array abaixo.
// Campos:
//   id          identificador único (texto curto, sem espaços)
//   nome        nome do catálogo
//   fabricante  montadora ou fabricante
//   marcas      lista de marcas usadas no filtro "Fabricante / marca"
//   grupo       "montadora" | "componentes"
//   categoria   texto curto (ex.: "Injeção / ignição / sensores", "Multimarcas")
//   descricao   descrição curta (até ~110 caracteres)
//   acesso      "Livre" | "Cadastro" | "Login" | "Assinatura" | "Indisponível" (não atende o Brasil) | "Bloqueado" (nega acesso a partir do Brasil)
//   testeBrasil resultado do teste do link feito no Brasil (23/09/2026)
//   busca       lista: "codigo" | "peca" | "veiculo" | "vin" | "placa" | "equivalencia"
//   oficial     true se for do próprio fabricante/montadora
//   vin         (opcional) só para catálogos com consulta por Chassi/VIN VALIDADA:
//               { acesso: "Livre"|"Cadastro"|"Login"|"Assinatura"|"Indisponível"|"Bloqueado",
//                 url (link mais direto para a consulta por VIN), observacao,
//                 teste (resultado do teste no Brasil), evidencia (URL), testadoEm }
//               Só incluir "vin" em busca quando houver evidência oficial.
//   restricaoBrasil (opcional) aviso de bloqueio/acesso negado a partir do Brasil
//   url         endereço verificado
//   observacao  (opcional) aviso exibido no cartão
//   verificadoEm data da última verificação do link
// =============================================================

export const GRUPOS_CATALOGOS_ONLINE = [
  { id: "montadora", titulo: "Montadoras", icone: "🚗" },
  { id: "componentes", titulo: "Fabricantes de Componentes", icone: "⚙️" },
];

export const TIPOS_ACESSO = ["Livre", "Cadastro", "Login", "Assinatura", "Indisponível", "Bloqueado"];

export const ROTULOS_BUSCA = {
  codigo: "Código",
  peca: "Peça",
  veiculo: "Veículo",
  vin: "Chassi/VIN",
  placa: "Placa",
  equivalencia: "Equivalência",
};

const V = "2026-09-23"; // teste final no navegador da loja, no Brasil

export const CATALOGOS_ONLINE = [
  // ------------------------------------------------------------
  // MONTADORAS
  // ------------------------------------------------------------

  // Chevrolet / GM
  {
    id: "cepchev",
    nome: "CepChev",
    fabricante: "Chevrolet / GM",
    marcas: ["Chevrolet / GM"],
    grupo: "montadora",
    categoria: "Peças por veículo",
    descricao:
      "Versão online do antigo catálogo eletrônico CepChev: códigos GM por modelo, grupo e assunto.",
    acesso: "Livre",
    busca: ["veiculo"],
    oficial: false,
    url: "https://cepchev.com.br/",
    observacao: "Site independente (não é da GM). Ao abrir, pede para marcar \"Confirme que é humano\" (Cloudflare). Confirme o código no Peça Chevrolet ou na concessionária.",
    testeBrasil: "Abre do Brasil, mas pede verificação anti-robô Cloudflare (\"Confirme que é humano\") antes de mostrar o conteúdo",
    verificadoEm: V,
  },
  {
    id: "peca-chevrolet",
    nome: "Peça Chevrolet",
    fabricante: "Chevrolet / GM",
    marcas: ["Chevrolet / GM"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Catálogo e loja oficial de peças genuínas GM/Chevrolet no Brasil, por modelo.",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://www.pecachevrolet.com.br/",
    testeBrasil: "Abriu: \"Peça Chevrolet | Peças e acessórios...\" (pede CEP, pode continuar sem)",
    verificadoEm: V,
  },
  {
    id: "gm-parts-eua",
    nome: "GM Parts Store (EUA)",
    fabricante: "Chevrolet / GM",
    marcas: ["Chevrolet / GM"],
    grupo: "montadora",
    categoria: "Peças genuínas / ACDelco",
    descricao:
      "Loja oficial GM e ACDelco dos EUA com busca por veículo. Útil para modelos globais.",
    acesso: "Bloqueado",
    busca: ["veiculo", "vin"],
    oficial: true,
    url: "https://parts.gmparts.com/",
    observacao: "Frota americana.",
    vin: {
      acesso: "Bloqueado",
      url: "https://parts.gmparts.com/",
      observacao: "Site bloqueia acesso do Brasil (Access Denied). Loja só para os EUA; não há página própria de VIN.",
      teste: "Acesso negado (Access Denied) ao abrir do Brasil",
      evidencia: "https://parts.gmparts.com/content/dam/gm-ecommerce/site-utility/documents/GM_Store_FAQ.pdf",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    restricaoBrasil: "Acesso negado ao abrir do Brasil (teste de 23/09/2026).",
    testeBrasil: "Access Denied ao abrir do Brasil",
    verificadoEm: V,
  },

  // Renault
  {
    id: "renault-mecanico-loja",
    nome: "Mecânico Renault — Loja Online",
    fabricante: "Renault",
    marcas: ["Renault"],
    grupo: "montadora",
    categoria: "Peças genuínas / Motrio",
    descricao:
      "Portal oficial Renault para mecânicos, com peças genuínas e Motrio e acesso ao catálogo de peças.",
    acesso: "Cadastro",
    busca: ["peca", "veiculo"],
    oficial: true,
    url: "https://mecanico.renault.com.br/loja-online",
    testeBrasil: "Abriu: \"Mecânico Renault - Loja Online\"; ofertas visíveis, com \"fazer login / cadastre-se\"",
    verificadoEm: V,
  },
  {
    id: "renault-motrio-pdf",
    nome: "Catálogo Motrio 2024 (PDF)",
    fabricante: "Renault",
    marcas: ["Renault"],
    grupo: "montadora",
    categoria: "Manutenção (PDF)",
    descricao:
      "Catálogo oficial Motrio com códigos, aplicações e equivalências de peças de manutenção.",
    acesso: "Livre",
    busca: ["codigo", "veiculo"],
    oficial: true,
    url: "https://mecanico.renault.com.br/stale/files/CatalogoMotrio_2024.pdf",
    observacao: "Não cobre injeção, sensores nem bobinas.",
    testeBrasil: "PDF abriu (RPA003524A _Catálogo_Motrio_v2)",
    verificadoEm: V,
  },

  // Fiat / Stellantis
  {
    id: "fiat-reparador",
    nome: "Fiat Reparador — Peças",
    fabricante: "Fiat (Stellantis)",
    marcas: ["Fiat"],
    grupo: "montadora",
    categoria: "Peças genuínas / Eurorepar",
    descricao:
      "Portal oficial Fiat para reparadores: peças genuínas, linha Classic by Mopar e Eurorepar.",
    acesso: "Cadastro",
    busca: ["peca", "veiculo"],
    oficial: true,
    url: "https://reparador.fiat.com.br/pecas.html",
    testeBrasil: "Abriu: \"Fiat: Peças\" (peças genuínas e Classic Line); portal com cadastro",
    verificadoEm: V,
  },
  {
    id: "mopar-brasil",
    nome: "Mopar Oficial Brasil",
    fabricante: "Stellantis (Fiat, Jeep, Peugeot, Citroën, Ram)",
    marcas: ["Fiat", "Jeep / Ram / Dodge", "Peugeot / Citroën"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Site oficial Mopar Brasil de peças e acessórios genuínos das marcas Stellantis.",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://www.moparoficial.com.br/",
    testeBrasil: "Abriu: \"Peças e Acessórios Genuínos Stellantis | MOPAR\" (vitrines de acessórios)",
    verificadoEm: V,
  },
  {
    id: "mopar-eua",
    nome: "Mopar Parts (EUA)",
    fabricante: "Stellantis (Jeep, Ram, Dodge, Chrysler)",
    marcas: ["Jeep / Ram / Dodge"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Catálogo oficial Mopar EUA de peças genuínas; o VIN Lookup identifica o veículo (mercado EUA).",
    acesso: "Livre",
    busca: ["veiculo", "vin", "peca"],
    oficial: true,
    url: "https://www.mopar.com/en-us/shop/parts.html",
    observacao: "Site dos EUA. Para chassi, o botão abre o VIN Lookup (identifica o veículo, não lista peças).",
    vin: {
      acesso: "Livre",
      url: "https://www.mopar.com/en-us/my-vehicle/vin-lookup.html",
      observacao: "Consulta do VIN só identifica o veículo (equipamentos e dados); não lista peças. Só veículos do mercado dos EUA.",
      teste: "Abriu do Brasil; página VIN Lookup com campo VIN",
      evidencia: "https://www.mopar.com/en-us/my-vehicle/vin-lookup.html",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu: \"Genuine Mopar Parts For Sale | Official Mopar Site\"; a consulta por VIN abre direto no VIN Lookup",
    verificadoEm: V,
  },
  {
    id: "stellantis-iop",
    nome: "Stellantis Independent Operator Portal",
    fabricante: "Stellantis (Jeep, Ram, Dodge, Chrysler)",
    marcas: ["Jeep / Ram / Dodge"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Portal oficial de informação de reparo Stellantis para oficinas independentes.",
    acesso: "Assinatura",
    busca: ["vin", "veiculo"],
    oficial: true,
    url: "https://stellantisiop.com/",
    vin: {
      acesso: "Assinatura",
      url: "https://stellantisiop.com/iop/app/landing/standard_access",
      observacao: "VIN digitado após login e assinatura paga (Jeep/Ram/Dodge/Chrysler, mercado EUA). Informação de reparo, não catálogo de peças.",
      teste: "Abriu do Brasil; portal com login",
      evidencia: "https://stellantisiop.com/iop/app/landing/standard_access",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu: portal com login; acesso por assinatura",
    verificadoEm: V,
  },

  // Peugeot / Citroën
  {
    id: "service-box",
    nome: "Service Box",
    fabricante: "Peugeot / Citroën (Stellantis)",
    marcas: ["Peugeot / Citroën"],
    grupo: "montadora",
    categoria: "Peças + informação técnica",
    descricao:
      "Portal oficial PSA/Stellantis: catálogo de peças, esquemas elétricos e procedimentos de reparo.",
    acesso: "Cadastro",
    busca: ["vin", "veiculo", "codigo"],
    oficial: true,
    url: "https://public.servicebox-parts.com/",
    observacao: "Alguns módulos podem ser pagos após o login.",
    vin: {
      acesso: "Cadastro",
      url: "https://public.servicebox-parts.com/",
      observacao: "Consulta por VIN após criar conta profissional e entrar; alguns módulos são pagos. Tela inicial em francês.",
      teste: "Abriu do Brasil; tela de login com 'Criar uma conta' (em francês)",
      evidencia: "https://distrigoparts.co.uk/service-box",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu: tela de login com \"Criar uma conta\" (em francês)",
    verificadoEm: V,
  },

  // Volkswagen / Audi
  {
    id: "pecas-vw",
    nome: "Peças VW — Loja Oficial",
    fabricante: "Volkswagen",
    marcas: ["Volkswagen"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Loja oficial VW do Brasil com catálogo de peças originais; busca simplificada por modelo e ano.",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://pecas.vw.com.br/",
    testeBrasil: "Abriu: \"Peças e Acessórios Originais Volkswagen | Loja Virtual Volkswagen\"",
    verificadoEm: V,
  },
  {
    id: "reparador-vw",
    nome: "Reparador VW",
    fabricante: "Volkswagen",
    marcas: ["Volkswagen"],
    grupo: "montadora",
    categoria: "Informação técnica",
    descricao:
      "Portal técnico oficial VW para reparadores independentes (motores EA211/EA189 e mais).",
    acesso: "Livre",
    busca: ["veiculo"],
    oficial: true,
    url: "https://www.reparadorvw.com.br/",
    observacao: "Dados de alinhamento, pneus e lubrificantes abertos; áreas exclusivas pedem cadastro.",
    testeBrasil: "Abriu: \"Reparadores VW | Portal Técnico...\" — dados de alinhamento, pneus e lubrificantes abertos sem login",
    verificadoEm: V,
  },
  {
    id: "erwin-vw-group",
    nome: "erWin — Grupo VW (informações)",
    fabricante: "Volkswagen / Audi / Škoda / SEAT",
    marcas: ["Volkswagen", "Audi"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Página oficial do erWin unificado do Grupo VW: reparo, manutenção e diagnóstico por assinatura.",
    acesso: "Indisponível",
    busca: ["vin", "veiculo"],
    oficial: true,
    url: "https://www.drivesomethinggreater.com/erwininfo",
    observacao: "Voltado a mercados europeus; Brasil não aparece no cronograma.",
    vin: {
      acesso: "Indisponível",
      url: "https://erwin.vwgroup-datahub.com/",
      observacao: "Licença paga (1 hora a 365 dias). O cadastro está liberado só em alguns países europeus; o Brasil não aparece entre os mercados atendidos.",
      teste: "Abriu do Brasil; portal erWin com licenças pagas",
      evidencia: "https://www.drivesomethinggreater.com/erwininfo",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    restricaoBrasil: "O erWin atende mercados europeus; o Brasil não aparece entre os países atendidos.",
    testeBrasil: "Página de informações abriu, mas o erWin não atende o Brasil (mercados europeus)",
    verificadoEm: V,
  },
  {
    id: "erwin-audi",
    nome: "erWin Audi",
    fabricante: "Audi",
    marcas: ["Audi"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Informação oficial de reparo Audi; licença por hora, dia, semana, mês ou ano.",
    acesso: "Indisponível",
    busca: ["veiculo"],
    oficial: true,
    url: "https://audi.erwin-store.com/",
    observacao: "Atende UE, Noruega, Suíça e Reino Unido.",
    restricaoBrasil: "O erWin atende só União Europeia, Noruega, Suíça e Reino Unido; o Brasil não é atendido.",
    testeBrasil: "Abriu, mas o site informa que o novo erWin atende só União Europeia, Noruega, Suíça e Reino Unido; outros países devem verificar disponibilidade",
    verificadoEm: V,
  },

  // Ford
  {
    id: "reparador-ford",
    nome: "Reparador Ford",
    fabricante: "Ford",
    marcas: ["Ford"],
    grupo: "montadora",
    categoria: "Informação técnica / Motorcraft",
    descricao:
      "Portal técnico oficial Ford para reparadores, com Motorcraft e e-book de injeção eletrônica.",
    acesso: "Cadastro",
    busca: ["veiculo"],
    oficial: true,
    url: "https://www.reparadorford.com.br/",
    testeBrasil: "Abriu: \"Reparador Ford - O Site do Reparador\" (linha Motorcraft; links Mercado Livre/Shopee)",
    verificadoEm: V,
  },
  {
    id: "pecas-ford",
    nome: "Peças Ford",
    fabricante: "Ford",
    marcas: ["Ford"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Página oficial Ford Brasil de peças genuínas, Motorcraft e Omnicraft, com link à loja oficial.",
    acesso: "Livre",
    busca: [],
    oficial: true,
    url: "https://www.ford.com.br/servico-ao-cliente/pecas-ford/",
    observacao: "Sem busca por código na própria página.",
    testeBrasil: "Abriu: \"Peças Ford\" (página institucional, link para loja no Mercado Livre)",
    verificadoEm: V,
  },

  // Toyota
  {
    id: "toyota-parts-eua",
    nome: "Toyota Parts Center (EUA)",
    fabricante: "Toyota",
    marcas: ["Toyota"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Catálogo oficial Toyota EUA com busca por código, palavra-chave ou VIN.",
    acesso: "Bloqueado",
    busca: ["codigo", "peca", "vin", "veiculo"],
    oficial: true,
    url: "https://autoparts.toyota.com/",
    observacao: "Frota americana; chassi brasileiro pode não decodificar.",
    vin: {
      acesso: "Bloqueado",
      url: "https://autoparts.toyota.com/",
      observacao: "Site bloqueia acesso do Brasil (erro 403). Só veículos dos EUA.",
      teste: "Erro 403 (Request blocked – CloudFront) ao abrir do Brasil",
      evidencia: "https://autoparts.toyota.com/",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    restricaoBrasil: "Erro 403 ao abrir do Brasil (teste de 23/09/2026).",
    testeBrasil: "Erro 403 (CloudFront) ao abrir do Brasil",
    verificadoEm: V,
  },
  {
    id: "toyota-tis",
    nome: "Toyota TIS",
    fabricante: "Toyota / Lexus",
    marcas: ["Toyota"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Manuais de reparo, esquemas elétricos, boletins e calibração de ECU (mercado EUA).",
    acesso: "Assinatura",
    busca: ["veiculo"],
    oficial: true,
    url: "https://techinfo.toyota.com/techInfoPortal/appmanager/t3/ti?_pageLabel=ti_whats_tis&_nfpb=true",
    testeBrasil: "Abriu: \"TIS\" — informação técnica de veículos da América do Norte, por assinatura",
    verificadoEm: V,
  },

  // Nissan
  {
    id: "nissan-pecas",
    nome: "Nissan — Peças e Produtos",
    fabricante: "Nissan",
    marcas: ["Nissan"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Página oficial Nissan Brasil de peças genuínas, com links para loja virtual e concessionárias.",
    acesso: "Livre",
    busca: [],
    oficial: true,
    url: "https://www.nissan.com.br/proprietarios/pecas-produtos.html",
    observacao: "Sem busca por código na própria página.",
    testeBrasil: "Abriu: \"PEÇAS E PRODUTOS\" (Nissan Brasil)",
    verificadoEm: V,
  },

  // Hyundai
  {
    id: "hyundai-mobis",
    nome: "Hyundai Mobis Brasil",
    fabricante: "Hyundai",
    marcas: ["Hyundai"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Site oficial Hyundai Mobis Brasil: peças genuínas por categoria, algumas com código e preço sugerido.",
    acesso: "Livre",
    busca: ["peca"],
    oficial: true,
    url: "https://hyundaimobis.com.br/produtos/pecas-de-reposicao/",
    testeBrasil: "Abriu: \"Peças Genuínas - Hyundai Mobis Brasil\"",
    verificadoEm: V,
  },
  {
    id: "hyundai-techinfo",
    nome: "Hyundai Service Website",
    fabricante: "Hyundai",
    marcas: ["Hyundai"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Manuais de oficina, diagnóstico elétrico e boletins técnicos oficiais (mercado EUA).",
    acesso: "Assinatura",
    busca: ["veiculo"],
    oficial: true,
    url: "https://www.hyundaitechinfo.com/",
    testeBrasil: "Abriu: \"Hyundai Service Website\" — login, cadastro e assinatura (veículos dos EUA)",
    verificadoEm: V,
  },

  // Kia
  {
    id: "kia-pecas",
    nome: "Kia Brasil — Peças de Reposição",
    fabricante: "Kia",
    marcas: ["Kia"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Formulário oficial para localizar peça genuína informando modelo, ano e chassi.",
    acesso: "Livre",
    busca: ["veiculo"],
    oficial: true,
    url: "https://www.kia.com.br/pecas-genuinas-reposicao",
    observacao: "Não é catálogo navegável: o chassi é pedido num formulário e a Kia retorna depois.",
    testeBrasil: "Abriu: \"Peças de reposição - Kia Brasil\" (formulário com chassi)",
    verificadoEm: V,
  },
  {
    id: "kia-kgis",
    nome: "Kia Global Information System (KGIS)",
    fabricante: "Kia",
    marcas: ["Kia"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Manuais de serviço, boletins, diagnóstico e reprogramação J2534 (mercado EUA).",
    acesso: "Assinatura",
    busca: ["veiculo"],
    oficial: true,
    url: "https://kiatechinfo.snapon.com/default.aspx",
    testeBrasil: "Abriu: \"Kia Global Information System (KGIS)\" — login com CAPTCHA; só veículos do mercado dos EUA",
    verificadoEm: V,
  },

  // Mitsubishi
  {
    id: "mit-pecas",
    nome: "MIT Peças",
    fabricante: "Mitsubishi",
    marcas: ["Mitsubishi"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Consulta oficial de peças genuínas e remanufaturadas Mitsubishi por veículo e estado.",
    acesso: "Livre",
    busca: ["veiculo"],
    oficial: true,
    url: "https://www.mitsubishimotors.com.br/servicos/mit-pecas",
    testeBrasil: "Abriu: \"MIT Peças mitsubishi...\" (Mitsubishi Motors Brasil)",
    verificadoEm: V,
  },
  {
    id: "mitsubishi-techinfo-eu",
    nome: "Mitsubishi Technical Information (Europa)",
    fabricante: "Mitsubishi",
    marcas: ["Mitsubishi"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Manuais de oficina, OBD, tempos padrão e boletins oficiais; acesso pago por período.",
    acesso: "Assinatura",
    busca: ["veiculo", "vin"],
    oficial: true,
    url: "https://www.mitsubishitechinfo.eu/",
    vin: {
      acesso: "Assinatura",
      url: "https://www.mitsubishitechinfo.eu/",
      observacao: "Identificação por VIN só para assinantes (a partir de €6/hora). Voltado à Europa, modelos a partir de 2011.",
      teste: "Abriu do Brasil; LOGIN / REGISTER",
      evidencia: "https://www.mitsubishitechinfo.eu/",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu: LOGIN / REGISTER, assinatura",
    verificadoEm: V,
  },

  // Mercedes-Benz
  {
    id: "mb-b2b-connect",
    nome: "B2B Connect",
    fabricante: "Mercedes-Benz",
    marcas: ["Mercedes-Benz"],
    grupo: "montadora",
    categoria: "Peças + informação técnica",
    descricao:
      "Portal oficial Mercedes para oficinas independentes: peças por VIN, WIS e diagnóstico XENTRY.",
    acesso: "Indisponível",
    busca: ["vin", "peca", "codigo", "veiculo"],
    oficial: true,
    url: "https://b2bconnect.mercedes-benz.com/gb",
    observacao: "WIS/XENTRY são serviços pagos. Versão Reino Unido.",
    vin: {
      acesso: "Indisponível",
      url: "https://b2bconnect.mercedes-benz.com/gb",
      observacao: "Não há versão Brasil: o cadastro é para oficinas dos países atendidos (Europa). Peças por VIN só após login.",
      teste: "Abriu do Brasil; o endereço /br redireciona para a versão da Alemanha",
      evidencia: "https://b2bconnect.mercedes-benz.com/gb",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    restricaoBrasil: "Não há versão Brasil do B2B Connect; o endereço /br vai para a versão da Alemanha.",
    testeBrasil: "Abriu (/gb), mas não há versão Brasil (o endereço /br vai para a Alemanha)",
    verificadoEm: V,
  },
  {
    id: "mb-pecas-brasil",
    nome: "Peças Genuínas Mercedes-Benz",
    fabricante: "Mercedes-Benz",
    marcas: ["Mercedes-Benz"],
    grupo: "montadora",
    categoria: "Peças genuínas",
    descricao:
      "Página oficial MB Brasil sobre peças genuínas e StarParts, com localizador de concessionárias.",
    acesso: "Livre",
    busca: ["veiculo"],
    oficial: true,
    url: "https://www2.mercedes-benz.com.br/passengercars/services/genuine-parts.html",
    observacao: "Sem catálogo online; direciona às concessionárias.",
    testeBrasil: "Abriu: \"Peças genuínas | Mercedes-Benz\" (Brasil)",
    verificadoEm: V,
  },

  // BMW
  {
    id: "bmw-aos",
    nome: "BMW Aftersales Online System (AOS)",
    fabricante: "BMW Group",
    marcas: ["BMW / MINI"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Portal oficial BMW para oficinas: diagnóstico ISTA e informação técnica AIR, pago por período.",
    acesso: "Assinatura",
    busca: [],
    oficial: true,
    url: "https://aos.bmwgroup.com/",
    testeBrasil: "Abriu: \"Aftersales online system\" — Login / Register now (acesso pago por período)",
    verificadoEm: V,
  },
  {
    id: "realoem",
    nome: "RealOEM",
    fabricante: "BMW / MINI",
    marcas: ["BMW / MINI"],
    grupo: "montadora",
    categoria: "Peças por diagrama",
    descricao:
      "Catálogo BMW/MINI com diagramas e part numbers; busca pelos últimos 7 dígitos do VIN.",
    acesso: "Livre",
    busca: ["vin", "codigo", "veiculo", "peca"],
    oficial: false,
    url: "https://www.realoem.com/bmw/enUS/select",
    observacao: "Não oficial, mas muito usado no setor.",
    vin: {
      acesso: "Livre",
      url: "https://www.realoem.com/bmw/enUS/select",
      observacao: "Usa só os 7 últimos dígitos do VIN (BMW/MINI). Site não oficial.",
      teste: "Abriu do Brasil; campo de VIN com 7 caracteres",
      evidencia: "https://www.realoem.com/bmw/enUS/select",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu: campo de VIN (7 dígitos)",
    verificadoEm: V,
  },

  // Volvo
  {
    id: "volvo-cars-tis",
    nome: "Volvo Cars — VIDA (Technical Information Shop)",
    fabricante: "Volvo Cars",
    marcas: ["Volvo"],
    grupo: "montadora",
    categoria: "Peças + informação técnica",
    descricao:
      "Assinatura VIDA oficial Volvo para independentes: catálogo de peças, reparo e diagnóstico.",
    acesso: "Indisponível",
    busca: ["vin", "codigo", "veiculo"],
    oficial: true,
    url: "https://tis.volvocars.biz/independent.html",
    vin: {
      acesso: "Indisponível",
      url: "https://tis.volvocars.biz/markets.html",
      observacao: "Assinatura VIDA vendida só nos mercados listados; o Brasil não está entre eles.",
      teste: "Abriu do Brasil; o Brasil não está na lista de mercados",
      evidencia: "https://tis.volvocars.biz/markets.html",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    restricaoBrasil: "A assinatura VIDA não é vendida para o Brasil (fora da lista de mercados).",
    testeBrasil: "Abriu, mas o Brasil não está entre os mercados do VIDA",
    verificadoEm: V,
  },
  {
    id: "volvo-pecas-caminhoes",
    nome: "Volvo Peças (caminhões e ônibus)",
    fabricante: "Volvo do Brasil",
    marcas: ["Volvo"],
    grupo: "montadora",
    categoria: "Linha pesada",
    descricao:
      "Loja oficial Volvo do Brasil de peças genuínas e reman para caminhões e ônibus.",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://www.volvopecas.com.br/catalogo-pecas",
    testeBrasil: "Abriu: \"Catálogo de Peças e Acessórios | Volvo Peças\"",
    verificadoEm: V,
  },
  {
    id: "volvo-trucks-catalogo",
    nome: "Catálogo de Peças Volvo Caminhões",
    fabricante: "Volvo Trucks",
    marcas: ["Volvo"],
    grupo: "montadora",
    categoria: "Linha pesada",
    descricao:
      "Catálogo-brochura oficial de peças Volvo Caminhões Brasil, por modelo e sistema.",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://www.volvotrucks.com.br/pt-br/services/parts-accessories/parts/parts-catalogue.html",
    testeBrasil: "Abriu: \"Assistência – Brochura de Peças Volvo | Volvo Trucks\"",
    verificadoEm: V,
  },

  // Jaguar / Land Rover
  {
    id: "jlr-topix",
    nome: "JLR TOPIx",
    fabricante: "Jaguar / Land Rover",
    marcas: ["Jaguar / Land Rover"],
    grupo: "montadora",
    categoria: "Informação técnica de reparo",
    descricao:
      "Portal oficial JLR: manuais, esquemas elétricos, boletins e campanhas por VIN.",
    acesso: "Assinatura",
    busca: ["vin"],
    oficial: true,
    url: "https://topix.jlrext.com/",
    vin: {
      acesso: "Livre",
      url: "https://topix.jlrext.com/topix/vehicle/lookupForm",
      observacao: "Sem login: consulta de campanhas de serviço/recall pendentes pelo VIN. Manuais e documentos técnicos exigem cadastro e assinatura.",
      teste: "Abriu do Brasil (em português); campo de VIN de 17 caracteres para visitante",
      evidencia: "https://topix.jlrext.com/topix/vehicle/lookupForm",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu em português; consulta de campanhas pelo VIN sem login",
    verificadoEm: V,
  },

  // ------------------------------------------------------------
  // FABRICANTES DE COMPONENTES
  // ------------------------------------------------------------

  // Bosch
  {
    id: "bosch-pesquisa-veiculos",
    nome: "Bosch Autopeças — Pesquisa de veículos",
    fabricante: "Bosch",
    marcas: ["Bosch"],
    grupo: "componentes",
    categoria: "Injeção / ignição / sensores",
    descricao: "Catálogo Bosch Brasil de autopeças com busca por veículo.",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://am.boschaftermarket.com/br/pt/pe%C3%A7as/",
    testeBrasil: "Abriu: Bosch Reposição Automotiva no Brasil (o próprio site usa este endereço para \"Pesquisa de veículos\")",
    verificadoEm: V,
  },
  {
    id: "bosch-pesquisa-produtos",
    nome: "Bosch Autopeças — Pesquisa de produtos",
    fabricante: "Bosch",
    marcas: ["Bosch"],
    grupo: "componentes",
    categoria: "Injeção / ignição / sensores",
    descricao: "Busca direta de produtos e códigos Bosch, sem selecionar veículo.",
    acesso: "Livre",
    busca: ["codigo", "peca"],
    oficial: true,
    url: "https://am.boschaftermarket.com/br/pt/pe%C3%A7as/product-search.html",
    testeBrasil: "Abriu: \"Peças de reposição Bosch para oficinas\" (Pesquisa de produtos)",
    verificadoEm: V,
  },

  // Magneti Marelli
  {
    id: "mm-cofap",
    nome: "Magneti Marelli Cofap — Catálogo",
    fabricante: "Magneti Marelli / Cofap",
    marcas: ["Magneti Marelli / Cofap"],
    grupo: "componentes",
    categoria: "Injeção / ignição / bombas",
    descricao:
      "Catálogo MM Cofap: busca por montadora, código/referência ou placa.",
    acesso: "Livre",
    busca: ["veiculo", "codigo", "placa", "equivalencia"],
    oficial: true,
    url: "https://mmcofap.com.br/",
    testeBrasil: "Abriu: \"Amortecedores Cofap e Injeção Eletrônica Magneti Marelli\" com a busca por montadora",
    verificadoEm: V,
  },
  {
    id: "mm-parts-services",
    nome: "Magneti Marelli Parts & Services — Catálogos",
    fabricante: "Magneti Marelli",
    marcas: ["Magneti Marelli / Cofap"],
    grupo: "componentes",
    categoria: "Catálogos PDF (internacional)",
    descricao: "Catálogos PDF internacionais Magneti Marelli por linha de produto.",
    acesso: "Livre",
    busca: ["peca"],
    oficial: true,
    url: "https://www.magnetimarelli-parts-and-services.com/products/catalogues.html",
    observacao: "Foco Europa.",
    testeBrasil: "Abriu: \"Magneti Marelli Parts & Services - Catalogues\"",
    verificadoEm: V,
  },

  // NGK / NTK
  {
    id: "ngk-consulta-rapida",
    nome: "NGK/NTK — Consulta Rápida",
    fabricante: "NGK / NTK (Niterra)",
    marcas: ["NGK / NTK"],
    grupo: "componentes",
    categoria: "Ignição / sonda lambda",
    descricao:
      "Consulta de velas, cabos, bobinas e sensores NGK/NTK por veículo e motor.",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://automotivo.ngkntk.com.br/?country=br&lang=pt",
    testeBrasil: "Abriu: \"NGK Automotivo\" com CONSULTA RÁPIDA (tipo, fabricante, veículo, produto, motor); o site redireciona para ?country=br&lang=pt",
    verificadoEm: V,
  },
  {
    id: "ngk-catalogos-pdf",
    nome: "NGK/NTK — Catálogos e Lançamentos",
    fabricante: "NGK / NTK (Niterra)",
    marcas: ["NGK / NTK"],
    grupo: "componentes",
    categoria: "Ignição / sensores (PDF)",
    descricao:
      "PDFs oficiais NGK/NTK: autos, motos, sensores NTK e velas aquecedoras.",
    acesso: "Livre",
    busca: ["veiculo"],
    oficial: true,
    url: "https://automotivo.ngkntk.com.br/catalogos-e-lancamentos/?country=br&lang=pt",
    testeBrasil: "Abriu: \"Catálogos e Lançamentos – NGK Automotivo\"",
    verificadoEm: V,
  },
  {
    id: "ngk-app",
    nome: "NGK/NTK — App de Catálogo",
    fabricante: "NGK / NTK (Niterra)",
    marcas: ["NGK / NTK"],
    grupo: "componentes",
    categoria: "Ignição / sensores (app)",
    descricao: "Página de download do app gratuito de catálogo NGK|NTK.",
    acesso: "Livre",
    busca: ["veiculo", "codigo"],
    oficial: true,
    url: "https://catexp.com.br/app/aplicativo?n=ngkntk",
    testeBrasil: "Abriu: \"NGK|NTK — Baixe grátis o aplicativo Catálogo NGK|NTK\" (no computador mostra só o convite para o app)",
    verificadoEm: V,
  },

  // Denso
  {
    id: "denso-find-my-part",
    nome: "DENSO Auto Parts — Find My Part",
    fabricante: "Denso",
    marcas: ["Denso"],
    grupo: "componentes",
    categoria: "Ignição / sensores / injeção",
    descricao:
      "Catálogo Denso (EUA) por veículo, VIN e referência cruzada.",
    acesso: "Livre",
    busca: ["veiculo", "vin", "codigo", "equivalencia"],
    oficial: true,
    url: "https://www.densoautoparts.com/catalogs/",
    observacao: "Foco EUA/Canadá.",
    vin: {
      acesso: "Livre",
      url: "https://www.densoautoparts.com/#find-my-part",
      observacao: "Escolha o tipo de veículo e 'VIN Search'. Catálogo da América do Norte: a frota brasileira pode não estar coberta.",
      teste: "Abriu do Brasil; Find My Part com opção 'VIN Search'",
      evidencia: "https://www.densoautoparts.com/#find-my-part",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu: \"Catalogs | DENSO Auto Parts\" com Find My Part",
    verificadoEm: V,
  },
  {
    id: "denso-velas",
    nome: "DENSO — Catálogo global de velas",
    fabricante: "Denso",
    marcas: ["Denso"],
    grupo: "componentes",
    categoria: "Ignição (velas)",
    descricao:
      "Catálogo global de velas Denso com busca por modelo e tabela de equivalência.",
    acesso: "Livre",
    busca: ["veiculo", "equivalencia"],
    oficial: true,
    url: "https://am.denso.com/plug-global/model-search/catalog/",
    testeBrasil: "Abriu: \"SPARK PLUG CATALOG DOWNLOAD – DENSO SPARK PLUG\" (PDFs por região)",
    verificadoEm: V,
  },

  // Delphi
  {
    id: "delphi-brasil",
    nome: "Delphi — Catálogo Fraga-Delphi",
    fabricante: "Delphi Technologies",
    marcas: ["Delphi"],
    grupo: "componentes",
    categoria: "Injeção / ignição / sensores",
    acesso: "Livre",
    busca: ["placa", "veiculo", "codigo"],
    oficial: true,
    url: "https://delphi.catalogofraga.com.br/",
    descricao: "Catálogo oficial Delphi Brasil (plataforma Fraga) com busca por placa, veículo e código.",
    testeBrasil: "Abriu: \"Catálogo Fraga-Delphi\" com busca por placa, veículo, código e busca geral (link corrigido)",
    verificadoEm: V,
  },

  // Continental / VDO
  {
    id: "continental-catalogos",
    nome: "Continental Aftermarket — Catálogos online",
    fabricante: "Continental / VDO",
    marcas: ["Continental / VDO"],
    grupo: "componentes",
    categoria: "Injeção / ignição / sensores",
    descricao:
      "Central de catálogos Continental/VDO: web, desktop, mobile e ATE freios.",
    acesso: "Livre",
    busca: ["veiculo", "codigo", "peca"],
    oficial: true,
    url: "https://www.continental-aftermarket.com/br-pt/cat%C3%A1logos/cat%C3%A1logos-online",
    testeBrasil: "Abriu: \"Catálogos Online\" (ATE, Web, Instalado no computador, Mobile)",
    verificadoEm: V,
  },
  {
    id: "vdo-catalogo-expresso",
    nome: "VDO — Catálogo Web",
    fabricante: "Continental / VDO",
    marcas: ["Continental / VDO"],
    grupo: "componentes",
    categoria: "Injeção / ignição / sensores",
    descricao:
      "Catálogo web VDO: injeção, ignição, sensores, bicos e bombas, filtro por montadora e modelo.",
    acesso: "Livre",
    busca: ["veiculo", "codigo", "peca"],
    oficial: true,
    url: "https://catalogoexpresso.com.br/vdo",
    testeBrasil: "Abriu: \"Catálogo de produtos - VDO\" (1.532 produtos, aplicações)",
    verificadoEm: V,
  },
  {
    id: "vdo-tecdoc",
    nome: "VDO — TecDoc Catalogue",
    fabricante: "Continental / VDO",
    marcas: ["Continental / VDO"],
    grupo: "componentes",
    categoria: "Multilinha (TecDoc)",
    descricao: "Catálogo VDO na plataforma TecDoc (TecAlliance).",
    acesso: "Livre",
    busca: ["veiculo", "codigo"],
    oficial: true,
    url: "https://web.tecalliance.net/vdo/pt/home",
    observacao: "Cobertura focada na Europa.",
    testeBrasil: "Abriu: \"VDO Catalogue\" (TecDoc, pesquisa por grupos de produtos, sem login)",
    verificadoEm: V,
  },

  // MTE-Thomson
  {
    id: "mte-cate",
    nome: "MTE-Thomson — Cat-E",
    fabricante: "MTE-Thomson",
    marcas: ["MTE-Thomson"],
    grupo: "componentes",
    categoria: "Sensores / sonda lambda",
    descricao:
      "Catálogo eletrônico MTE-Thomson com busca por placa, veículo, código ou equivalente.",
    acesso: "Livre",
    busca: ["veiculo", "codigo", "placa", "equivalencia"],
    oficial: true,
    url: "https://cate.mte-thomson.com.br/pt/br",
    testeBrasil: "Abriu: \"CatE - Catálogo eletrônico MTE-THOMSON\" (pesquisa por veículo e por código)",
    verificadoEm: V,
  },
  {
    id: "mte-pdf",
    nome: "MTE-Thomson — Catálogos PDF",
    fabricante: "MTE-Thomson",
    marcas: ["MTE-Thomson"],
    grupo: "componentes",
    categoria: "Sensores (PDF)",
    descricao: "PDFs MTE-Thomson: linha completa, diesel, moto, ABS e EGTS.",
    acesso: "Livre",
    busca: ["veiculo", "codigo"],
    oficial: true,
    url: "https://www.mte-thomson.com.br/catalogos/",
    testeBrasil: "Abriu: \"Catálogos - MTE-THOMSON\"",
    verificadoEm: V,
  },

  // TSA
  {
    id: "tsa-produtos",
    nome: "TSA — Produtos",
    fabricante: "TSA",
    marcas: ["TSA"],
    grupo: "componentes",
    categoria: "Sensores / bombas / reguladores",
    descricao:
      "Catálogo TSA: sensores de nível e rotação, bombas e reguladores, por veículo ou código.",
    acesso: "Livre",
    busca: ["veiculo", "codigo"],
    oficial: true,
    url: "https://tsadobrasil.com.br/produtos",
    testeBrasil: "Abriu: \"Produtos TSA do Brasil\" com aplicações",
    verificadoEm: V,
  },
  {
    id: "tsa-downloads",
    nome: "TSA — Downloads (PDF, app, desktop)",
    fabricante: "TSA",
    marcas: ["TSA"],
    grupo: "componentes",
    categoria: "Sensores (PDF/app)",
    descricao: "Catálogo TSA em PDF, app e desktop; o PDF pede formulário.",
    acesso: "Cadastro",
    busca: ["veiculo", "codigo"],
    oficial: true,
    url: "https://www.tsadobrasil.com.br/downloads",
    testeBrasil: "Abriu: \"Downloads TSA do Brasil\" — PDF liberado após preencher formulário",
    verificadoEm: V,
  },

  // DS
  {
    id: "ds-industria",
    nome: "DS — Catálogo de produtos",
    fabricante: "DS Indústria de Peças",
    marcas: ["DS"],
    grupo: "componentes",
    categoria: "Sensores / injeção / bombas",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://www.ds.ind.br/pt",
    observacao: "Filtro de produtos livre; o catálogo completo é enviado após preencher um formulário.",
    descricao: "Sensores, bicos, bombas e reguladores DS com busca avançada por montadora, modelo e linha.",
    testeBrasil: "Abriu: página em português com busca avançada e downloads (link corrigido)",
    verificadoEm: V,
  },

  // 3-RHO
  {
    id: "3rho",
    nome: "3-RHO — Produtos",
    fabricante: "3-RHO",
    marcas: ["3-RHO"],
    grupo: "componentes",
    categoria: "Sensores / interruptores",
    descricao: "Sensores e interruptores 3-RHO, com PDF, catálogo desktop e app.",
    acesso: "Livre",
    busca: ["peca"],
    oficial: true,
    url: "https://www.3rho.com.br/pt-br/produtos/categorias",
    testeBrasil: "Abriu: \"Produtos\" 3-RHO (linha de produtos, Catálogo PDF, Catálogo Express, aplicativo)",
    verificadoEm: V,
  },

  // Kostal
  {
    id: "kostal",
    nome: "KOSTAL — Peças para Reposição",
    fabricante: "Kostal",
    marcas: ["Kostal"],
    grupo: "componentes",
    categoria: "Elétrica / interruptores / sensores",
    descricao: "Catálogo Kostal de interruptores, sensores e comandos elétricos, com filtros de busca.",
    acesso: "Livre",
    busca: ["veiculo", "peca"],
    oficial: true,
    url: "https://www.kostalbrasil.com.br/catalogo/pecas",
    testeBrasil: "Abriu: \"Peças para Reposição KOSTAL\" com filtros de busca (link corrigido)",
    verificadoEm: V,
  },

  // MS Motorservice / Pierburg
  {
    id: "ms-catweb",
    nome: "MS Motorservice — CatWeb",
    fabricante: "MS Motorservice (KS / Pierburg)",
    marcas: ["MS Motorservice (KS / Pierburg)"],
    grupo: "componentes",
    categoria: "Motor / sensores / EGR / bombas",
    descricao:
      "Catálogo KS/Pierburg com busca por código, veículo, motor, ano e combustível.",
    acesso: "Livre",
    busca: ["codigo", "veiculo"],
    oficial: true,
    url: "https://catweb.ms-motorservice.com.br/",
    testeBrasil: "Abriu: \"Motorservice – Catálogo de Produtos\" (código, montadora, veículo, motor, ano)",
    verificadoEm: V,
  },
  {
    id: "ms-loja",
    nome: "MS Motorservice — Loja B2B",
    fabricante: "MS Motorservice",
    marcas: ["MS Motorservice (KS / Pierburg)"],
    grupo: "componentes",
    categoria: "Motor",
    descricao: "Loja B2B MS Motorservice: login com número de cliente; busca sem registro é limitada.",
    acesso: "Login",
    busca: ["codigo"],
    oficial: true,
    url: "https://shop.ms-motorservice.com.br/",
    testeBrasil: "Abriu (redireciona para onlineshop.ms-motorservice.com): login de cliente com número de cliente; há \"acesso sem registro\" limitado à busca de produtos",
    verificadoEm: V,
  },

  // Mahle
  {
    id: "mahle-catalogo",
    nome: "MAHLE — Catálogo",
    fabricante: "Mahle",
    marcas: ["Mahle"],
    grupo: "componentes",
    categoria: "Motor / filtros / térmico",
    descricao: "Catálogo Mahle Brasil com busca por placa, veículo, código e produto/medida.",
    acesso: "Livre",
    busca: ["placa", "veiculo", "codigo"],
    oficial: true,
    url: "https://catalogo.mahle.com/",
    testeBrasil: "Abriu: \"Catálogo Mahle\" com busca por placa, veículo, código e produto/medida (link corrigido)",
    verificadoEm: V,
  },

  // Valeo
  {
    id: "valeo",
    nome: "Valeo Service — Catálogo online",
    fabricante: "Valeo",
    marcas: ["Valeo"],
    grupo: "componentes",
    categoria: "Embreagem / térmico / elétrica",
    descricao:
      "Catálogo Valeo Brasil: busca por referência, veículo ou categoria, sem cadastro.",
    acesso: "Livre",
    busca: ["codigo", "veiculo", "peca"],
    oficial: true,
    url: "https://www.valeoservice.com.br/pt-br/catalogo",
    testeBrasil: "Abriu: \"Catálogo Online Valeo\" — \"Acesso gratuito e imediato: não requer cadastro\"",
    verificadoEm: V,
  },

  // Hella
  {
    id: "hella",
    nome: "HELLA — Catálogo online",
    fabricante: "Hella (Forvia)",
    marcas: ["Hella"],
    grupo: "componentes",
    categoria: "Iluminação / elétrica / sensores",
    descricao: "Catálogo HELLA na plataforma TecDoc, com pesquisa por veículo ou artigo, sem login.",
    acesso: "Livre",
    busca: ["veiculo", "codigo"],
    oficial: true,
    url: "https://web.tecalliance.net/hella/pt/home",
    observacao: "Cobertura focada no mercado europeu.",
    testeBrasil: "Abriu: catálogo \"HELLA\" (TecDoc) com pesquisa avançada, sem login (link corrigido)",
    verificadoEm: V,
  },

  // Nakata / Fras-le
  {
    id: "nakata",
    nome: "Catálogo Nakata",
    fabricante: "Nakata (Fras-le Mobility)",
    marcas: ["Fras-le / Nakata"],
    grupo: "componentes",
    categoria: "Suspensão / direção",
    descricao: "Catálogo eletrônico Nakata em português, com busca geral e referência cruzada.",
    acesso: "Livre",
    busca: ["codigo", "veiculo", "equivalencia"],
    oficial: true,
    url: "https://www.catalogonakata.com.br/",
    testeBrasil: "Abriu: \"Catálogo Eletrônico Nakata\" em português (link corrigido)",
    verificadoEm: V,
  },
  {
    id: "auto-experts",
    nome: "Auto Experts",
    fabricante: "Fras-le Mobility (Fras-le, Fremax, Nakata, Controil...)",
    marcas: ["Fras-le / Nakata"],
    grupo: "componentes",
    categoria: "Freios / suspensão",
    descricao:
      "Catálogo integrado de 9 marcas com busca por placa, chassi, código e referência cruzada.",
    acesso: "Livre",
    busca: ["placa", "vin", "codigo", "veiculo", "equivalencia"],
    oficial: true,
    url: "https://www.autoexperts.parts/pt/br",
    observacao: "Cadastro gratuito opcional libera recursos extras.",
    vin: {
      acesso: "Cadastro",
      url: "https://www.autoexperts.parts/pt/br",
      observacao: "Busca por chassi exige conta gratuita (entrar ou criar conta). Catálogo brasileiro.",
      teste: "Abriu do Brasil; ao clicar em 'Busque por número do chassi' pede para entrar ou criar conta",
      evidencia: "https://www.autoexperts.parts/pt/br",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu; busca por chassi pede conta gratuita",
    verificadoEm: V,
  },

  // Multimarcas
  {
    id: "tecdoc-brasil",
    nome: "TecDoc Catalogue Brasil",
    fabricante: "TecAlliance (multimarcas)",
    marcas: ["Multimarcas"],
    grupo: "componentes",
    categoria: "Multimarcas",
    descricao:
      "Catálogo multimarcas de referência: aplicações, equivalências e referência original.",
    acesso: "Cadastro",
    busca: ["codigo", "peca", "veiculo", "vin", "placa"],
    oficial: true,
    url: "https://tecalliance.com.br/tecdoc-catalogue/",
    observacao: "Plano grátis sem placa/chassi; busca por placa e chassi só no Premium (pago).",
    vin: {
      acesso: "Assinatura",
      url: "https://web.tecalliance.net/tecdocbr/qc/register",
      observacao: "Busca por chassi só no plano Premium (pago). O plano grátis exige cadastro e não tem placa nem chassi.",
      teste: "Abriu do Brasil; tela de cadastro TecDoc Brasil",
      evidencia: "https://tecalliance.com.br/produto/tecdoc-catalogue-brasil-premium/",
      testadoEm: "23/09/2026, no computador da loja (Brasil)",
    },
    testeBrasil: "Abriu: \"TecDoc Catalogue – TecAlliance do Brasil\"",
    verificadoEm: V,
  },
  {
    id: "baixe-catalogo",
    nome: "Baixe Catálogo",
    fabricante: "Agregador (multimarcas)",
    marcas: ["Multimarcas"],
    grupo: "componentes",
    categoria: "Multimarcas",
    descricao:
      "Agregador gratuito com centenas de catálogos de fabricantes de autopeças.",
    acesso: "Livre",
    busca: ["placa", "peca", "codigo"],
    oficial: false,
    url: "https://baixecatalogo.com.br/",
    observacao: "Não é fonte primária: confirme no catálogo do fabricante.",
    testeBrasil: "Abriu: \"Baixe Catálogo - Download de Catálogos de Autopeças\"",
    verificadoEm: V,
  },
  {
    id: "fraga-placa",
    nome: "Fraga — Busca por Placa",
    fabricante: "Fraga Inteligência Automotiva",
    marcas: ["Multimarcas"],
    grupo: "componentes",
    categoria: "Multimarcas",
    descricao:
      "Base de aplicações Fraga (padrão dos distribuidores) com busca por placa em planos pagos.",
    acesso: "Assinatura",
    busca: ["placa", "veiculo", "codigo"],
    oficial: true,
    url: "https://fraga.com.br/en/search-by-license-plate/",
    observacao: "Produto B2B para integrar ao sistema da loja.",
    testeBrasil: "Abriu: \"SEARCH BY LICENSE PLATE – Fraga\" (página em inglês do serviço B2B; não há página equivalente em português confirmada)",
    verificadoEm: V,
  },
];
